name: Maven Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Add GITHUB_TOKEN here to authenticate
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build, Test, and Package with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Verify TXT file existence
      - name: Verify TXT file existence
        run: |
          if ls target/*.txt 1> /dev/null 2>&1; then
            echo "TXT file exists"
          else
            echo "No TXT files found in target/"; exit 1
          fi

      # Step 6: Upload TXT artifact
      - name: Upload TXT artifact
        uses: actions/upload-artifact@v3
        with:
          name: txtfile  # Artifact name
          path: target/*.txt  # Path to the artifact.