trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile'
      mavenOptions: '-Xmx1024m'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      mavenOptions: '-Xmx1024m'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      mavenOptions: '-Xmx1024m'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
