name: Maven Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
 security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Add GITHUB_TOKEN here to authenticate
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build, Test, and Package with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Evaluate with Sonatype IQ
      - name: iq policy eval
        id: evaluate
        uses: sonatype/actions@v1.3.0
        with:
            iq-server-url: https://489348249c16.ngrok.app
            username: ${{ secrets.IQ_USERNAME }}
            password: ${{ secrets.IQ_PSWRD }}
            application-id: scademo
            scan-targets: '**/*'
            enable-callflow: true 
            sarif-file: 'sariffile.sarif'
            upload-sarif-file: 'true'
  
